// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpgBAeDc1g-_VWRk1ngWzMh-o2O7l7kRs',
    appId: '1:219118859670:web:343d585fcb2d9a234c99b7',
    messagingSenderId: '219118859670',
    projectId: 'notepad-72c87',
    authDomain: 'notepad-72c87.firebaseapp.com',
    storageBucket: 'notepad-72c87.appspot.com',
    measurementId: 'G-GDNEHZ0LJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTdSZCxlE5YF5Ssh0R7mFbBZnAQiqqWJM',
    appId: '1:219118859670:android:d1fd60e85bcb4a8d4c99b7',
    messagingSenderId: '219118859670',
    projectId: 'notepad-72c87',
    storageBucket: 'notepad-72c87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_jO4GyahCP3DCuHOzQ_og3xfouV0yTyI',
    appId: '1:219118859670:ios:2ca5900b871e28f14c99b7',
    messagingSenderId: '219118859670',
    projectId: 'notepad-72c87',
    storageBucket: 'notepad-72c87.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_jO4GyahCP3DCuHOzQ_og3xfouV0yTyI',
    appId: '1:219118859670:ios:2ca5900b871e28f14c99b7',
    messagingSenderId: '219118859670',
    projectId: 'notepad-72c87',
    storageBucket: 'notepad-72c87.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpgBAeDc1g-_VWRk1ngWzMh-o2O7l7kRs',
    appId: '1:219118859670:web:e818b9f438c025004c99b7',
    messagingSenderId: '219118859670',
    projectId: 'notepad-72c87',
    authDomain: 'notepad-72c87.firebaseapp.com',
    storageBucket: 'notepad-72c87.appspot.com',
    measurementId: 'G-QQ38EGEKHC',
  );
}
